// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PurchaseSiteParser.DataContext;

#nullable disable

namespace PurchaseSiteParser.Migrations
{
    [DbContext(typeof(PurchaseContext))]
    [Migration("20241105134800_PurchaseCardsAndResultsAdded")]
    partial class PurchaseCardsAndResultsAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PurchaseSiteParser.Data.Entities.Purchases.PurchaseCard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Law")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseObject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchaseParsingResultId")
                        .HasColumnType("integer");

                    b.Property<decimal>("StartPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseParsingResultId");

                    b.ToTable("PurchaseCards");
                });

            modelBuilder.Entity("PurchaseSiteParser.Data.Entities.Purchases.PurchaseParsingResult", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("id"));

                    b.Property<string>("PagesPeriod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PurchaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PurchasesListCount")
                        .HasColumnType("integer");

                    b.HasKey("id");

                    b.ToTable("PurchaseParsingResults");
                });

            modelBuilder.Entity("PurchaseSiteParser.Data.Entities.Purchases.PurchaseCard", b =>
                {
                    b.HasOne("PurchaseSiteParser.Data.Entities.Purchases.PurchaseParsingResult", "PurchaseParsingResult")
                        .WithMany("PurchasesCardsList")
                        .HasForeignKey("PurchaseParsingResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseParsingResult");
                });

            modelBuilder.Entity("PurchaseSiteParser.Data.Entities.Purchases.PurchaseParsingResult", b =>
                {
                    b.Navigation("PurchasesCardsList");
                });
#pragma warning restore 612, 618
        }
    }
}
